---
- name: Install docker ctop
  ansible.builtin.include_tasks: ctop.yml
  when:
    - ansible_os_family == 'Debian'

- name: Check if /usr/local/bin/compose-switch exists
  ansible.builtin.stat:
    path: /usr/local/bin/compose-switch
  register: dockertools_compose_switch_status

- name: Setup docker compose-switch
  when: not dockertools_compose_switch_status.stat.exists
  block:
    - name: Install curl which is needed for running compose-switch installer
      ansible.builtin.apt:
        name:
          - curl
        update_cache: true
        install_recommends: false

    - name: Fetch docker compose-switch install script
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/docker/compose-switch/master/install_on_linux.sh
        return_content: true
      register: dockertools_compose_switch_installer

    - name: Run docker compose-switch installer  # noqa: no-changed-when
      ansible.builtin.command:
        cmd: bash
        stdin: "{{ dockertools_compose_switch_installer.content }}"
