---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: waja.dockertools

#  pre_tasks:
#    - name: Update apt cache.
#      ansible.builtin.apt: update_cache=yes cache_valid_time=600
#      when: ansible_os_family == 'Debian'
